name: TenUtilV3
main: Ten.TenUtil.Main
version: 4.0.0
author: Ten#0010
commands:
  hyväksy:
    description: Hyväksy palvelimen säännöt annetulla salasanalla.
    usage: /hyväksy salasana
  säännöt:
    description: Avaa säännöt selaimessa.
    usage: /säännöt
